#!/bin/bash -xv

# changed the above from /bin/sh to /bin/bash as per /etc/rc.multi
PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Do not start services besides tty's if we're running single-user.
if [ -n "$(grep ttys cmdline)" ]
then
   # only start ttys
   runsvchdir ttys
elif [ -n "$(grep single cmdline)" ]
then
   # ttys + syslog + klog
   runsvchdir single
else
   # taken the below from /etc/rc.multi
   runsvchdir multi
   /etc/rc.multi
fi

exec env - PATH=$PATH \
runsvdir -P /var/run/runit/runsvdir/current 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
