#!/bin/bash
exec 2>&1

PATH=/command:/sbin:/bin:/usr/sbin:/usr/bin

sync && sync && sync

if [ -x /etc/runit/reboot ]
then
 export RUNLEVEL=6
else
 export RUNLEVEL=0
fi

# Load configuration
. /etc/rc.conf
# Shutdown services
if [ "${SERVICES[*]}" ]; then
   for service in "${SERVICES[@]}"; do
      R_SERVICES=($service ${R_SERVICES[@]})
   done
   for service in "${R_SERVICES[@]}"; do
      /etc/rc.d/$service stop &> /tmp/rc.$$
      /usr/bin/logger -t $service -f /tmp/rc.$$
      /bin/rm -f /tmp/rc.$$
   done
fi

echo 'Waiting for services to stop...'
shopt -s extglob
sv -w196 force-stop /etc/runit/runsvdir/current/!(tty1)
sv exit /etc/runit/runsvdir/current/!(tty1)

echo 'Shutdown...'
/etc/rc.shutdown
