#!/bin/sh -xv
exec 2>&1

PATH=/sbin:/bin:/usr/sbin:/usr/bin

sync && sync && sync

if [ -x /var/run/runit/reboot ]
then
 export RUNLEVEL=6
else
 export RUNLEVEL=0
fi

echo 'Waiting for services to stop...'
sv -w196 shutdown /var/run/runit/runsvdir/current/*
# sleep to show me any service that is not dying and correct it
#  to respond to a TERM or CONT
sleep 10
# do not send a kill here, /etc/rc.shutdown sends a TERM
#  to all processes and then sends a KILL to all processes
# sv force-shutdown /var/run/runit/runsvdir/current/*

# echo 'Switching to single...'
# runsvchdir single

echo 'Shutdown...'
PREVLEVEL=2 /etc/rc.shutdown
